#!/usr/bin/perl

# Copyright 2012-2016 Jason Hancock
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This file is part of the nagios-puppet bundle that can be found
# at https://github.com/jasonhancock/nagios-puppet

use strict;
use warnings;

use Nagios::Plugin;
use Nagios::Plugin::Threshold;

my $np = Nagios::Plugin->new(
     usage => "Usage: %s [-c|--critical=<threshold> ] [ -w|--warning=<threshold> ] "
        . "[-f|--file=<path_to_file> ] [ -n|--numlines=<number_of_lines> ] ",
     shortname => 'Compile Time',
   );

$np->add_arg(
    spec => 'warning|w=s',
    help => '-w, --warning=Seconds'
);

$np->add_arg(
    spec => 'critical|c=s',
    help => '-c, --critical=Seconds'
);

$np->add_arg(
    spec    => 'file|f=s',
    help    => '-f, --file=Log file to parse. Defaults to /var/log/messages',
    default => '/var/log/messages'
);

$np->add_arg(
    spec    => 'numlines|n=s',
    help    => '-n, --numlines=Number of lines of logfile to examine. Defaults to 100.',
    default => 100
);

$np->getopts;

unless ( defined $np->opts->warning || defined $np->opts->critical ) {
    $np->nagios_die( " you didn't supply a threshold argument " );
}


my $cmd = sprintf('tail -n %d %s', $np->opts->numlines, $np->opts->file);
my @lines = `$cmd`;

my $sum=0;
my $count=0;

foreach my $line(@lines) {
    if($line=~m/Compiled catalog for .+ in environment .+ in (\d+\.\d+) seconds/) {
        $sum += $1;
        $count++;
    }
}

my $avg = sprintf('%.2f', $count > 0 ? $sum/$count : 0);

$np->add_perfdata( 
    label => 'catalog compile time',
    value => $avg,
    uom   => 'seconds',
    threshold => Nagios::Plugin::Threshold->set_thresholds(
        warning  => $np->opts->warning,
        critical => $np->opts->critical,
    )
);

##############################################################################
## check the result against the defined warning and critical thresholds,
## output the result and exit
$np->nagios_exit(
    return_code => $np->check_threshold($avg),
    message => " Average catalog compilation time: $avg seconds"
);
